name: richokun
favicon: null
layout_spectrum: 0.45293
typography_spectrum: 0.43348
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#c6c6c6'
    - '#545454'
    - '#8a8a8a'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
