typography_spectrum: 0.06884605786763132
color:
  brandColors:
    - '#703030'
    - '#2F343B'
    - '#7E827A'
    - '#E3CDA4'
    - '#C77966'
  brandStrength: 0.2332924536895007
  lightness: 0.44957621046341956
  saturation: 0.8059139805845916
  rhythmicContrast: 0.6485881335102022
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2528674143832177
analytics:
  google: null
  facebook: null
  twitter: null
name: richokun
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: I saw you
    id: d386d258-c45d-43fe-8ebe-a5d6084bbeaf
    type: content
  - name: That ole' thang (just in time)
    id: b1b7848b-dbda-43f9-9e14-8c70fd1e1a35
    type: content
  - name: The Dance of the Cottonwood
    id: 475d5e0f-0947-41c9-be36-7bd0f967b931
    type: content
  - name: hold no one beholden
    id: 826d82be-fc88-4a4d-8c49-2992ebe4e031
    type: content
  - name: The Inner You
    id: f1b4e989-a50e-4db0-b9d9-150cd11f69a0
    type: content
  - name: Opossum
    id: 6ea3c8e9-504c-4b25-86cb-c9427d7d6f75
    type: content
  - name: you sent the winds
    id: 0e2d5ed3-a170-4046-b71a-fce30d9f7ea6
    type: content
  - name: no fanfare at all
    id: ce5796de-79eb-424a-866d-d5f92c0eee45
    type: content
  - name: Walk in the ordinary
    id: 0f1a5519-3ca9-4c40-948d-d6d3ab8857fc
    type: content
  - name: Today I am a Cardinal
    id: 28a32c4f-6122-4815-851c-972bfb2adc0e
    type: content
  - name: from my spirit I belong
    id: 00479f29-bb76-42a6-ab84-bdd3bf2e8a09
    type: content
  - name: Am I
    id: 26371ae2-bb6b-41f4-bc94-436ff05c229d
    type: content
  - name: Living
    id: d441caaf-79b4-4e7b-8089-a1c6c7ee61f6
    type: content
  - name: DoBe
    id: 00ae9b5b-3f5e-4fbf-a61c-4d510c102ddc
    type: content
  - name: Unlikely friends
    id: 1c41455e-3dcc-493b-8a92-9d7e8b315ed2
    type: content
  - name: playful like a child
    id: 7dd9341f-cd2c-45d0-836f-8e7d0cb4aec3
    type: content
  - name: a magical quest
    id: 76ca5c30-de82-458a-818c-5f2faa78452e
    type: content
  - name: I see my breath
    id: 7ad9d255-0bff-425f-833f-0a949378401f
    type: content
  - name: the great pretender
    id: ddf697c3-89ec-4ef1-a554-7b91103454bb
    type: content
  - name: good news
    id: c700bc96-de2d-4e19-bc37-a34c73b46754
    type: content
  - name: advantages
    id: 619f8547-4531-4167-bd06-988dd2dc9bac
    type: content
  - name: My Dreams have come
    id: f7b1fb92-32ab-498e-9729-0ac8b18bf356
    type: content
  - name: Intuition
    id: 7e92c6c3-429d-47b7-b669-b95b9a5dfaa3
    type: content
  - name: Now I allow
    id: c0bcca57-f0cd-489d-af43-fbd14946d0cc
    type: content
  - name: If I see in you
    id: e18e769e-25cb-4d02-9f7f-6a061b9a8e6d
    type: content
  - name: a tiny little dot
    id: cc7087fc-dd4e-4ade-a16f-46b692999dfd
    type: content
  - name: a path of gold
    id: 4c13da3f-ddd2-4988-af49-910a2b3b1852
    type: content
  - name: In divine fashion
    id: 98775009-6fca-4ebd-b08d-471f574cbf6d
    type: content
  - name: an ageless essence
    id: 0092a500-c207-479c-954a-b051fea14e3f
    type: content
favicon: null
title: Rich Okun
purpose: []
