name: richokun
favicon: null
layout_spectrum: 0.45293
typography_spectrum: 0.43348
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2120'
    - '#455719'
    - '#bc9658'
    - '#feebb8'
    - '#7e001f'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
