name: richokun
favicon: null
layout_spectrum: 0.1736057261005044
typography_spectrum: 0.3772605746053159
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9284a'
    - '#ffffff'
    - '#45fb3a'
    - '#b99f68'
    - '#250000'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.15938604436814785
purpose: []
