name: richokun
favicon: null
layout_spectrum: 0.1736057261005044
typography_spectrum: 0.3772605746053159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6893350447062403
  lightness: 0.25154270930215716
  saturation: 0.6034215877298266
  rhythmicContrast: 0.15938604436814785
purpose: []
