name: richokun
favicon: null
layout_spectrum: 0.43172
typography_spectrum: 0.43348
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d3d2'
    - '#fcfcfc'
    - '#7a7a84'
    - '#040406'
    - '#47464c'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
