name: richokun
favicon: null
layout_spectrum: 0.04519
typography_spectrum: 0.43348
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d89da5'
    - '#000000'
    - '#6f1118'
    - '#5f4f49'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
