name: richokun
favicon: null
layout_spectrum: 0.86625
typography_spectrum: 0.43348
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#617e52'
    - '#84a369'
    - '#392e2c'
    - '#b18775'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
