name: richokun
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87121
title: Rich Okun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030000'
    - '#52514c'
    - '#c7c4be'
    - '#b19f85'
  brandStrength: 0.0625
  lightness: 0.0625
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
